[build]
  command = "./build.sh"
  publish = "dist"
  functions = "lambda/dist"
[build.environment]
  # maybe look at https://github.com/puppeteer/puppeteer/releases to find out which release matches with revision
  CHROMIUM_REVISION = "756035"
[[headers]]
  for = "/static/fonts/*.*.*"
  [headers.values]
	cache-control = '''
	public,
	max-age=86400,
	must-revalidate'''
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = false
[[headers]]
  for = "/"
  [headers.values]
	content-security-policy = "base-uri 'self'; object-src 'none'; script-src 'self'; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com/; connect-src 'self' https://api.github.com/; img-src 'self' https: data:; media-src 'none'; child-src 'none'; frame-src https://player.vimeo.com/ https://www.youtube.com/"
[[headers]]
  for = "/*"
  [header.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
[[headers]]
  for = "/*.*.js"
  [headers.values]
	cache-control = '''
	public,
	max-age=86400,
	must-revalidate'''
[[headers]]
  for = "/*.*.css"
  [headers.values]
	cache-control = '''
	public,
	max-age=86400,
	must-revalidate'''
